# Generated by Django 4.2.6 on 2024-01-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentclinicfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('matric_no', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('courses', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('phone_num', models.CharField(max_length=20)),
                ('file_1', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
